name: Cross-Platform Build & Test

on: [push, pull_request]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux GCC
            os: ubuntu-latest
            c_compiler: gcc

          - name: Linux Clang
            os: ubuntu-latest
            c_compiler: clang

          - name: Windows MSVC
            on: windows-latest
            cc: cl

    steps:
    - uses: actions/checkout@v6

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=ON
      env:
        CC: ${{ matrix.cc }}

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      working-directory: build
      run: ctest -C Release --output-on-failure --output-junit test-results.xml

    - name: Publish Test Results
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: Tests (${{ matrix.name }})
        path: build/test-results.xml
        reporter: java-junit